# Generated by Django 3.2.6 on 2021-09-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_Archive', '0002_auto_20210909_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='verified',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
