# Generated by Django 3.2.6 on 2021-10-19 20:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books_Archive', '0004_alter_books_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
