# Generated by Django 3.2.13 on 2022-05-07 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Books_Archive', '0005_alter_books_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='books',
            name='uploaded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
